- hosts: server
  become: true
  gather_facts: true
  
  vars:
    jenkins_hostname: localhost
    java_packages:
      - java-1.8.0-openjdk-devel
    
    pip_install_packages:
      - name: docker

  pre_tasks:
  - name: update all packages 
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest

  - name: install  nano  
    yum:
      name: nano
      state: installed

  - name: install wget
    yum:
      name: wget
      state: installed 

  - name: Install epel release
    yum: 
      name: epel-release
      state: installed

  
  - name: Using wget to install jenkins repo
    shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    args:
      warn: no

  - name: install jenkins packages
    
    shell: rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key 
    args:
      warn: no

  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: geerlingguy.java

  tasks:

  - name: install jenkins
    yum:
      name: jenkins
      state: installed

  - name: Restart service jenkins, in all cases
    service:
      name: jenkins
      state: restarted

  - name: Enable service jenkins, and not touch the state
    service:
      name: jenkins
      enabled: yes

     
